### ISSUE TITLE
Excecution Halted

### ISSUE THREAD

**Issue by emryoliver** [slimsuite/chromsyn#2]
```
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Registered S3 method overwritten by 'rvest':
  method            from
  read_xml.response xml2
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.1.1       ✔ purrr   0.3.2  
✔ tibble  2.1.1       ✔ dplyr   0.8.0.1
✔ tidyr   0.8.3       ✔ stringr 1.4.0  
✔ readr   1.3.1       ✔ forcats 0.4.0  
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
[Fri Aug  4 08:16:43 2023] ../rje_load.R
[Fri Aug  4 08:16:43 2023] Sequence FOFN File: sequences.fofn
[Fri Aug  4 08:16:43 2023] No region data file given.
[Fri Aug  4 08:16:43 2023] TIDK FOFN file: tidk.fofn
[Fri Aug  4 08:16:43 2023] Assembly gap FOFN file: gaps.fofn
[Fri Aug  4 08:16:43 2023] features table FOFN file not found: ft.fofn
[Fri Aug  4 08:16:43 2023] BUSCO full FOFN file: busco.fofn
[Fri Aug  4 08:16:43 2023] BUSCO FOFN file: busco.fofn
[Fri Aug  4 08:16:43 2023] #RCODE Setup complete.
[Fri Aug  4 08:16:43 2023] #FOFN 3 filenames loaded from sequences.fofn
[Fri Aug  4 08:16:43 2023] #FOFN 3 filenames loaded from busco.fofn
[Fri Aug  4 08:16:43 2023] #FOFN 3 filenames after filtering to recognised genomes.
[Fri Aug  4 08:16:43 2023] Genomes (order=LIST): ensPLATY, ensPOTO1, ensTAMM
Joining, by = "Genome"
[Fri Aug  4 08:16:43 2023] #FOFN 3 filenames loaded from tidk.fofn
[Fri Aug  4 08:16:43 2023] #FOFN 3 filenames after filtering to recognised genomes.
Joining, by = "Genome"
[Fri Aug  4 08:16:43 2023] #FOFN 3 filenames loaded from gaps.fofn
[Fri Aug  4 08:16:43 2023] #FOFN 3 filenames after filtering to recognised genomes.
Joining, by = "Genome"
[Fri Aug  4 08:16:43 2023] #GENOME  3 genomes: ensPLATY, ensPOTO1, ensTAMM
[Fri Aug  4 08:16:43 2023] ensPLATY...
Error in all_of(keepfields) : could not find function "all_of"
Calls: seqTable ... <Anonymous> -> vars_select_eval -> map_if -> map -> .f
Execution halted

```
```
Error in all_of(keepfields) : could not find function "all_of"
Calls: seqTable ... <Anonymous> -> vars_select_eval -> map_if -> map -> .f
Execution halted
```
I was able to create all of the files but then it failed. Am I missing some package? Any help would be greatly appreciated!

**Comment by cabbagesofdoom** [comment]
Hi. You might just want to try updating your packages. This is what I am currently running with:

```
── Attaching core tidyverse packages ─────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
─
```

I've not done any testing with different versions, so I am not sure how far back you go and still have the code work.

**Comment by cabbagesofdoom** [comment]
I was just wondering if you were able to solve the problem with updated packages, or were things still failing?

**Comment by emryoliver** [comment]
Hey Rich,

Unfortunately, even with fully updated packages, I could not get the
program to run.

Emry Brannan, M.S.
Ph.D. candidate, R. O'Neill Lab <https://roneill.lab.uconn.edu/>
University of Connecticut
Department of Molecular and Cell Biology

**Comment by cabbagesofdoom** [comment]
Was it the same error? As far as I know, `all_of()` is a standard tidyverse function. You could try with the latest ChromSyn version, in case there was just something strange going on. Did you set `chromfill=X`?

I suspect you've found another solution now, but let me know if you want to try to get it working, else I will close the issue.

**Comment by emryoliver** [comment]
Yes, it was the same error. I am going to work this week on trying to fix
the issue! I will let you know how it goes, thanks!

Emry Brannan, M.S.
Ph.D. candidate, R. O'Neill Lab <https://roneill.lab.uconn.edu/>
University of Connecticut
Department of Molecular and Cell Biology

**Comment by emryoliver** [comment]
I was able to get it to run successfully! Thanks so much!

Emry Brannan, M.S.
Ph.D. candidate, R. O'Neill Lab <https://roneill.lab.uconn.edu/>
University of Connecticut
Department of Molecular and Cell Biology

**Comment by cabbagesofdoom** [comment]
Excellent. I shall close the ticket but please get in touch or raise another issue if you have questions. I am added features from time to time and not all of them get documented straight away, so there might already be easy ways to achieve certain outcomes.
