### ISSUE TITLE
Conflicts tidyverse

### ISSUE THREAD

**Issue by bifidoman** [slimsuite/chromsyn#3]
Hi

I got conflict problems due to the tidy verse package. 
something like:

Conflicts --------------------------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
i Use the conflicted package to force all conflicts to become errors
[Fri Dec  1 15:36:58 2023] chromsyn/rje_load.R
[Fri Dec  1 15:36:58 2023] Sequence FOFN File: sequences.fofn
[Fri Dec  1 15:36:58 2023] Cannot find sequence FOFN file: sequences.fofn

Here is the solution:
1) install package conflicted (e.g. install.packages("conflicted", lib="/usr/lib/R/library"))

Than add to line 122 of chromosyn.R:
---------------------------------------------------
library(conflicted)  
library(tidyverse)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
----------------------------------------------

And it will work

**Comment by cabbagesofdoom** [comment]
Thanks for the tip. I don't think those conflicts are fatal, they're just warnings. I've not seen them cause problems.
